// @generated by packages/semconv/scripts/generate.ts — do not edit

// Attribute names

/** Name of the MicroVM image the instance was launched from. */
export const ATTR_KAGERO_MICROVM_IMAGE_NAME = "kagero.microvm.image.name" as const;

/** Version of the MicroVM image. */
export const ATTR_KAGERO_MICROVM_IMAGE_VERSION = "kagero.microvm.image.version" as const;

/** Configured baseline size of the MicroVM. */
export const ATTR_KAGERO_MICROVM_SIZE = "kagero.microvm.size" as const;

/** Lifecycle event that occurred on the MicroVM. /ready and /validate are build hooks and never emit lifecycle events (build time is quiescent), so they are not members. */
export const ATTR_KAGERO_LIFECYCLE_EVENT = "kagero.lifecycle.event" as const;

/** Tenant identifier extracted from runHookPayload when configured. */
export const ATTR_KAGERO_TENANT_ID = "kagero.tenant.id" as const;

/** Session identifier extracted from runHookPayload when configured. */
export const ATTR_KAGERO_SESSION_ID = "kagero.session.id" as const;

/** Wall-clock seconds the MicroVM spent suspended, observed on resume. */
export const ATTR_KAGERO_SUSPEND_DURATION_SECONDS = "kagero.suspend.duration_seconds" as const;

/** Failure detail on kagero.lifecycle.degraded records. Error text is unbounded — never a metric label. */
export const ATTR_KAGERO_ERROR = "kagero.error" as const;

/** Outcome of relaying a hook to the app, on lifecycle event records. */
export const ATTR_KAGERO_APP_RESULT = "kagero.app.result" as const;

/** Whether the app process had already exited when the hook ran. */
export const ATTR_KAGERO_APP_EXITED = "kagero.app.exited" as const;

/** Name of the lifecycle hook being relayed. */
export const ATTR_KAGERO_HOOK_NAME = "kagero.hook.name" as const;

/** Outcome of a relayed hook. */
export const ATTR_KAGERO_HOOK_STATUS = "kagero.hook.status" as const;

/** Which hook produced the summary. */
export const ATTR_KAGERO_USAGE_CAUSE = "kagero.usage.cause" as const;

/** RUNNING wall-clock seconds since /run. */
export const ATTR_KAGERO_USAGE_RUNNING_SECONDS = "kagero.usage.running_seconds" as const;

/** vCPU-seconds above the MicroVM baseline. */
export const ATTR_KAGERO_USAGE_BURST_VCPU_SECONDS = "kagero.usage.burst_vcpu_seconds" as const;

/** GiB-seconds above the MicroVM baseline. */
export const ATTR_KAGERO_USAGE_BURST_GIB_SECONDS = "kagero.usage.burst_gib_seconds" as const;

/** Total seconds spent suspended. */
export const ATTR_KAGERO_USAGE_SUSPEND_SECONDS = "kagero.usage.suspend_seconds" as const;

/** /suspend count this boot. */
export const ATTR_KAGERO_USAGE_SUSPENDS = "kagero.usage.suspends" as const;

/** /resume count this boot. */
export const ATTR_KAGERO_USAGE_RESUMES = "kagero.usage.resumes" as const;

/** ARN of the durable execution this span belongs to. */
export const ATTR_KAGERO_DURABLE_EXECUTION_ARN = "kagero.durable.execution.arn" as const;

/** Human-readable name of the durable execution. */
export const ATTR_KAGERO_DURABLE_EXECUTION_NAME = "kagero.durable.execution.name" as const;

/** Number of replays (re-executions) observed in the assembled history. */
export const ATTR_KAGERO_DURABLE_REPLAY_COUNT = "kagero.durable.replay_count" as const;

/** Kind of durable step a span represents. */
export const ATTR_KAGERO_DURABLE_STEP_KIND = "kagero.durable.step.kind" as const;

/** Name of the durable step (user-defined). */
export const ATTR_KAGERO_DURABLE_STEP_NAME = "kagero.durable.step.name" as const;

/** Attempt number for retried steps. */
export const ATTR_KAGERO_DURABLE_ATTEMPT = "kagero.durable.attempt" as const;

/** Terminal or current status of a durable execution or step. */
export const ATTR_KAGERO_DURABLE_STATUS = "kagero.durable.status" as const;

/** Identifier of one distributed load-test run. */
export const ATTR_KAGERO_K6_RUN_ID = "kagero.k6.run.id" as const;

/** Shard index (0-based) of a k6 segment within a run. */
export const ATTR_KAGERO_K6_SHARD_ID = "kagero.k6.shard.id" as const;

/** Constant "kagero" — anchors the agent's log streams and metric series (Loki {service_name="kagero"}). Safe on metrics. */
export const ATTR_SERVICE_NAME = "service.name" as const;

/** MicroVM instance identifier received at /run (microvmId). Logs and traces only. */
export const ATTR_SERVICE_INSTANCE_ID = "service.instance.id" as const;

/** Always "aws". */
export const ATTR_CLOUD_PROVIDER = "cloud.provider" as const;

/** AWS region the MicroVM runs in. */
export const ATTR_CLOUD_REGION = "cloud.region" as const;

/** MicroVM instance identifier (faas-facing copy of service.instance.id). */
export const ATTR_FAAS_INSTANCE = "faas.instance" as const;

// Metric names

/** Seconds the MicroVM spent in RUNNING state, observed by the agent. */
export const METRIC_KAGERO_MICROVM_RUNNING_SECONDS = "kagero.microvm.running_seconds" as const;

/** vCPU-seconds consumed above the configured baseline. */
export const METRIC_KAGERO_MICROVM_BURST_VCPU_SECONDS =
  "kagero.microvm.burst_vcpu_seconds" as const;

/** GiB-seconds of memory consumed above the configured baseline. The `{gib}` annotation keeps the Prometheus OTLP unit suffix at "_seconds" (already the name suffix), so translation inserts nothing. */
export const METRIC_KAGERO_MICROVM_BURST_MEMORY_GIB_SECONDS =
  "kagero.microvm.burst_memory_gib_seconds" as const;

/** Number of lifecycle transitions, labelled by kagero.lifecycle.event. */
export const METRIC_KAGERO_MICROVM_LIFECYCLE_TRANSITIONS =
  "kagero.microvm.lifecycle_transitions" as const;

/** Distribution of suspend-to-resume wall-clock durations. */
export const METRIC_KAGERO_MICROVM_SUSPEND_DURATION_SECONDS =
  "kagero.microvm.suspend_duration_seconds" as const;

/** Runtime-hook relay outcomes, labelled by kagero.hook.name and kagero.hook.status. */
export const METRIC_KAGERO_MICROVM_HOOK_RESULTS = "kagero.microvm.hook_results" as const;

/** Completed durable executions assembled by the stitcher, labelled by kagero.durable.status. */
export const METRIC_KAGERO_DURABLE_EXECUTIONS = "kagero.durable.executions" as const;

/** Wall-clock duration of assembled durable executions. */
export const METRIC_KAGERO_DURABLE_EXECUTION_DURATION_SECONDS =
  "kagero.durable.execution.duration_seconds" as const;

/** Replay (re-execution) events observed across assembled executions. */
export const METRIC_KAGERO_DURABLE_REPLAYS = "kagero.durable.replays" as const;

// Metric definitions (name → shape)

export const KAGERO_METRICS = {
  "kagero.microvm.running_seconds": { instrument: "counter", unit: "s" },
  "kagero.microvm.burst_vcpu_seconds": { instrument: "counter", unit: "{vcpu}s" },
  "kagero.microvm.burst_memory_gib_seconds": { instrument: "counter", unit: "{gib}s" },
  "kagero.microvm.lifecycle_transitions": { instrument: "counter", unit: "{transition}" },
  "kagero.microvm.suspend_duration_seconds": { instrument: "histogram", unit: "s" },
  "kagero.microvm.hook_results": { instrument: "counter", unit: "{hook}" },
  "kagero.durable.executions": { instrument: "counter", unit: "{execution}" },
  "kagero.durable.execution.duration_seconds": { instrument: "histogram", unit: "s" },
  "kagero.durable.replays": { instrument: "counter", unit: "{replay}" },
} as const;

// Enumerated attribute values

/** Values of `kagero.lifecycle.event`. */
export const LIFECYCLE_EVENT_VALUES = [
  "run",
  "suspend",
  "resume",
  "terminate",
  "degraded",
] as const;
export type LifecycleEvent = (typeof LIFECYCLE_EVENT_VALUES)[number];

/** Values of `kagero.app.result`. */
export const APP_RESULT_VALUES = ["ok", "unimplemented", "no_listener", "failed"] as const;
export type AppResult = (typeof APP_RESULT_VALUES)[number];

/** Values of `kagero.hook.status`. */
export const HOOK_STATUS_VALUES = ["ok", "timeout", "error", "unimplemented"] as const;
export type HookStatus = (typeof HOOK_STATUS_VALUES)[number];

/** Values of `kagero.usage.cause`. */
export const USAGE_CAUSE_VALUES = ["suspend", "terminate"] as const;
export type UsageCause = (typeof USAGE_CAUSE_VALUES)[number];

/** Values of `kagero.durable.step.kind`. */
export const DURABLE_STEP_KIND_VALUES = [
  "step",
  "wait",
  "callback",
  "retry",
  "chained",
  "invoke",
  "context",
] as const;
export type DurableStepKind = (typeof DURABLE_STEP_KIND_VALUES)[number];

/** Values of `kagero.durable.status`. */
export const DURABLE_STATUS_VALUES = [
  "succeeded",
  "failed",
  "timed_out",
  "stopped",
  "running",
] as const;
export type DurableStatus = (typeof DURABLE_STATUS_VALUES)[number];

// ADR-008: attributes that must never appear on metric labels

export const METRIC_LABEL_FORBIDDEN = [
  "kagero.tenant.id",
  "kagero.session.id",
  "kagero.suspend.duration_seconds",
  "kagero.error",
  "kagero.usage.cause",
  "kagero.usage.running_seconds",
  "kagero.usage.burst_vcpu_seconds",
  "kagero.usage.burst_gib_seconds",
  "kagero.usage.suspend_seconds",
  "kagero.usage.suspends",
  "kagero.usage.resumes",
  "kagero.durable.execution.arn",
  "kagero.durable.execution.name",
  "kagero.durable.replay_count",
  "kagero.durable.step.name",
  "kagero.durable.attempt",
  "service.instance.id",
  "faas.instance",
] as const;
export const METRIC_LABEL_ALLOWED = [
  "kagero.microvm.image.name",
  "kagero.microvm.image.version",
  "kagero.microvm.size",
  "kagero.lifecycle.event",
  "kagero.app.result",
  "kagero.app.exited",
  "kagero.hook.name",
  "kagero.hook.status",
  "kagero.durable.step.kind",
  "kagero.durable.status",
  "kagero.k6.run.id",
  "kagero.k6.shard.id",
  "service.name",
  "cloud.provider",
  "cloud.region",
] as const;

// Registry completeness sets

export const ALL_ATTRIBUTE_IDS = [
  "kagero.microvm.image.name",
  "kagero.microvm.image.version",
  "kagero.microvm.size",
  "kagero.lifecycle.event",
  "kagero.tenant.id",
  "kagero.session.id",
  "kagero.suspend.duration_seconds",
  "kagero.error",
  "kagero.app.result",
  "kagero.app.exited",
  "kagero.hook.name",
  "kagero.hook.status",
  "kagero.usage.cause",
  "kagero.usage.running_seconds",
  "kagero.usage.burst_vcpu_seconds",
  "kagero.usage.burst_gib_seconds",
  "kagero.usage.suspend_seconds",
  "kagero.usage.suspends",
  "kagero.usage.resumes",
  "kagero.durable.execution.arn",
  "kagero.durable.execution.name",
  "kagero.durable.replay_count",
  "kagero.durable.step.kind",
  "kagero.durable.step.name",
  "kagero.durable.attempt",
  "kagero.durable.status",
  "kagero.k6.run.id",
  "kagero.k6.shard.id",
  "service.name",
  "service.instance.id",
  "cloud.provider",
  "cloud.region",
  "faas.instance",
] as const;
export const ALL_METRIC_NAMES = [
  "kagero.microvm.running_seconds",
  "kagero.microvm.burst_vcpu_seconds",
  "kagero.microvm.burst_memory_gib_seconds",
  "kagero.microvm.lifecycle_transitions",
  "kagero.microvm.suspend_duration_seconds",
  "kagero.microvm.hook_results",
  "kagero.durable.executions",
  "kagero.durable.execution.duration_seconds",
  "kagero.durable.replays",
] as const;
