//! @generated by packages/semconv/scripts/generate.ts — do not edit

//! kagero semantic-convention constants.
#![allow(dead_code)]

/// Name of the MicroVM image the instance was launched from.
pub const ATTR_KAGERO_MICROVM_IMAGE_NAME: &str = "kagero.microvm.image.name";
/// Version of the MicroVM image.
pub const ATTR_KAGERO_MICROVM_IMAGE_VERSION: &str = "kagero.microvm.image.version";
/// Configured baseline size of the MicroVM.
pub const ATTR_KAGERO_MICROVM_SIZE: &str = "kagero.microvm.size";
/// Lifecycle event that occurred on the MicroVM. /ready and /validate are build hooks and never emit lifecycle events (build time is quiescent), so they are not members.
pub const ATTR_KAGERO_LIFECYCLE_EVENT: &str = "kagero.lifecycle.event";
/// Tenant identifier extracted from runHookPayload when configured.
pub const ATTR_KAGERO_TENANT_ID: &str = "kagero.tenant.id";
/// Session identifier extracted from runHookPayload when configured.
pub const ATTR_KAGERO_SESSION_ID: &str = "kagero.session.id";
/// Wall-clock seconds the MicroVM spent suspended, observed on resume.
pub const ATTR_KAGERO_SUSPEND_DURATION_SECONDS: &str = "kagero.suspend.duration_seconds";
/// Failure detail on kagero.lifecycle.degraded records. Error text is unbounded — never a metric label.
pub const ATTR_KAGERO_ERROR: &str = "kagero.error";
/// Outcome of relaying a hook to the app, on lifecycle event records.
pub const ATTR_KAGERO_APP_RESULT: &str = "kagero.app.result";
/// Whether the app process had already exited when the hook ran.
pub const ATTR_KAGERO_APP_EXITED: &str = "kagero.app.exited";
/// Name of the lifecycle hook being relayed.
pub const ATTR_KAGERO_HOOK_NAME: &str = "kagero.hook.name";
/// Outcome of a relayed hook.
pub const ATTR_KAGERO_HOOK_STATUS: &str = "kagero.hook.status";
/// Which hook produced the summary.
pub const ATTR_KAGERO_USAGE_CAUSE: &str = "kagero.usage.cause";
/// RUNNING wall-clock seconds since /run.
pub const ATTR_KAGERO_USAGE_RUNNING_SECONDS: &str = "kagero.usage.running_seconds";
/// vCPU-seconds above the MicroVM baseline.
pub const ATTR_KAGERO_USAGE_BURST_VCPU_SECONDS: &str = "kagero.usage.burst_vcpu_seconds";
/// GiB-seconds above the MicroVM baseline.
pub const ATTR_KAGERO_USAGE_BURST_GIB_SECONDS: &str = "kagero.usage.burst_gib_seconds";
/// Total seconds spent suspended.
pub const ATTR_KAGERO_USAGE_SUSPEND_SECONDS: &str = "kagero.usage.suspend_seconds";
/// /suspend count this boot.
pub const ATTR_KAGERO_USAGE_SUSPENDS: &str = "kagero.usage.suspends";
/// /resume count this boot.
pub const ATTR_KAGERO_USAGE_RESUMES: &str = "kagero.usage.resumes";
/// ARN of the durable execution this span belongs to.
pub const ATTR_KAGERO_DURABLE_EXECUTION_ARN: &str = "kagero.durable.execution.arn";
/// Human-readable name of the durable execution.
pub const ATTR_KAGERO_DURABLE_EXECUTION_NAME: &str = "kagero.durable.execution.name";
/// Number of replays (re-executions) observed in the assembled history.
pub const ATTR_KAGERO_DURABLE_REPLAY_COUNT: &str = "kagero.durable.replay_count";
/// Kind of durable step a span represents.
pub const ATTR_KAGERO_DURABLE_STEP_KIND: &str = "kagero.durable.step.kind";
/// Name of the durable step (user-defined).
pub const ATTR_KAGERO_DURABLE_STEP_NAME: &str = "kagero.durable.step.name";
/// Attempt number for retried steps.
pub const ATTR_KAGERO_DURABLE_ATTEMPT: &str = "kagero.durable.attempt";
/// Terminal or current status of a durable execution or step.
pub const ATTR_KAGERO_DURABLE_STATUS: &str = "kagero.durable.status";
/// Identifier of one distributed load-test run.
pub const ATTR_KAGERO_K6_RUN_ID: &str = "kagero.k6.run.id";
/// Shard index (0-based) of a k6 segment within a run.
pub const ATTR_KAGERO_K6_SHARD_ID: &str = "kagero.k6.shard.id";
/// Constant "kagero" — anchors the agent's log streams and metric series (Loki {service_name="kagero"}). Safe on metrics.
pub const ATTR_SERVICE_NAME: &str = "service.name";
/// MicroVM instance identifier received at /run (microvmId). Logs and traces only.
pub const ATTR_SERVICE_INSTANCE_ID: &str = "service.instance.id";
/// Always "aws".
pub const ATTR_CLOUD_PROVIDER: &str = "cloud.provider";
/// AWS region the MicroVM runs in.
pub const ATTR_CLOUD_REGION: &str = "cloud.region";
/// MicroVM instance identifier (faas-facing copy of service.instance.id).
pub const ATTR_FAAS_INSTANCE: &str = "faas.instance";

/// Seconds the MicroVM spent in RUNNING state, observed by the agent.
pub const METRIC_KAGERO_MICROVM_RUNNING_SECONDS: &str = "kagero.microvm.running_seconds";
/// vCPU-seconds consumed above the configured baseline.
pub const METRIC_KAGERO_MICROVM_BURST_VCPU_SECONDS: &str = "kagero.microvm.burst_vcpu_seconds";
/// GiB-seconds of memory consumed above the configured baseline. The `{gib}` annotation keeps the Prometheus OTLP unit suffix at "_seconds" (already the name suffix), so translation inserts nothing.
pub const METRIC_KAGERO_MICROVM_BURST_MEMORY_GIB_SECONDS: &str =
    "kagero.microvm.burst_memory_gib_seconds";
/// Number of lifecycle transitions, labelled by kagero.lifecycle.event.
pub const METRIC_KAGERO_MICROVM_LIFECYCLE_TRANSITIONS: &str =
    "kagero.microvm.lifecycle_transitions";
/// Distribution of suspend-to-resume wall-clock durations.
pub const METRIC_KAGERO_MICROVM_SUSPEND_DURATION_SECONDS: &str =
    "kagero.microvm.suspend_duration_seconds";
/// Runtime-hook relay outcomes, labelled by kagero.hook.name and kagero.hook.status.
pub const METRIC_KAGERO_MICROVM_HOOK_RESULTS: &str = "kagero.microvm.hook_results";
/// Completed durable executions assembled by the stitcher, labelled by kagero.durable.status.
pub const METRIC_KAGERO_DURABLE_EXECUTIONS: &str = "kagero.durable.executions";
/// Wall-clock duration of assembled durable executions.
pub const METRIC_KAGERO_DURABLE_EXECUTION_DURATION_SECONDS: &str =
    "kagero.durable.execution.duration_seconds";
/// Replay (re-execution) events observed across assembled executions.
pub const METRIC_KAGERO_DURABLE_REPLAYS: &str = "kagero.durable.replays";

/// ADR-008: attributes that must never appear on metric labels.
pub const METRIC_LABEL_FORBIDDEN: &[&str] = &[
    "kagero.tenant.id",
    "kagero.session.id",
    "kagero.suspend.duration_seconds",
    "kagero.error",
    "kagero.usage.cause",
    "kagero.usage.running_seconds",
    "kagero.usage.burst_vcpu_seconds",
    "kagero.usage.burst_gib_seconds",
    "kagero.usage.suspend_seconds",
    "kagero.usage.suspends",
    "kagero.usage.resumes",
    "kagero.durable.execution.arn",
    "kagero.durable.execution.name",
    "kagero.durable.replay_count",
    "kagero.durable.step.name",
    "kagero.durable.attempt",
    "service.instance.id",
    "faas.instance",
];

/// Every registered attribute id — the source-drift test asserts that
/// every `kagero.*`/`service.*` literal in agent sources is listed here.
pub const ALL_ATTRIBUTE_IDS: &[&str] = &[
    "kagero.microvm.image.name",
    "kagero.microvm.image.version",
    "kagero.microvm.size",
    "kagero.lifecycle.event",
    "kagero.tenant.id",
    "kagero.session.id",
    "kagero.suspend.duration_seconds",
    "kagero.error",
    "kagero.app.result",
    "kagero.app.exited",
    "kagero.hook.name",
    "kagero.hook.status",
    "kagero.usage.cause",
    "kagero.usage.running_seconds",
    "kagero.usage.burst_vcpu_seconds",
    "kagero.usage.burst_gib_seconds",
    "kagero.usage.suspend_seconds",
    "kagero.usage.suspends",
    "kagero.usage.resumes",
    "kagero.durable.execution.arn",
    "kagero.durable.execution.name",
    "kagero.durable.replay_count",
    "kagero.durable.step.kind",
    "kagero.durable.step.name",
    "kagero.durable.attempt",
    "kagero.durable.status",
    "kagero.k6.run.id",
    "kagero.k6.shard.id",
    "service.name",
    "service.instance.id",
    "cloud.provider",
    "cloud.region",
    "faas.instance",
];
/// Every registered metric name.
pub const ALL_METRIC_NAMES: &[&str] = &[
    "kagero.microvm.running_seconds",
    "kagero.microvm.burst_vcpu_seconds",
    "kagero.microvm.burst_memory_gib_seconds",
    "kagero.microvm.lifecycle_transitions",
    "kagero.microvm.suspend_duration_seconds",
    "kagero.microvm.hook_results",
    "kagero.durable.executions",
    "kagero.durable.execution.duration_seconds",
    "kagero.durable.replays",
];

/// Values of `kagero.lifecycle.event`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LifecycleEvent {
    Run,
    Suspend,
    Resume,
    Terminate,
    /// A hook or telemetry step failed at runtime; the workload continued (ADR-004).
    Degraded,
}

impl LifecycleEvent {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Run => "run",
            Self::Suspend => "suspend",
            Self::Resume => "resume",
            Self::Terminate => "terminate",
            Self::Degraded => "degraded",
        }
    }
}

impl TryFrom<&str> for LifecycleEvent {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, ()> {
        match value {
            "run" => Ok(Self::Run),
            "suspend" => Ok(Self::Suspend),
            "resume" => Ok(Self::Resume),
            "terminate" => Ok(Self::Terminate),
            "degraded" => Ok(Self::Degraded),
            _ => Err(()),
        }
    }
}

/// Values of `kagero.app.result`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AppResult {
    Ok,
    /// The app returned 404; treated as not implemented.
    Unimplemented,
    /// The app does not listen on the app hook port.
    NoListener,
    /// Relay failed (connect refused, timeout, non-2xx).
    Failed,
}

impl AppResult {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Ok => "ok",
            Self::Unimplemented => "unimplemented",
            Self::NoListener => "no_listener",
            Self::Failed => "failed",
        }
    }
}

impl TryFrom<&str> for AppResult {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, ()> {
        match value {
            "ok" => Ok(Self::Ok),
            "unimplemented" => Ok(Self::Unimplemented),
            "no_listener" => Ok(Self::NoListener),
            "failed" => Ok(Self::Failed),
            _ => Err(()),
        }
    }
}

/// Values of `kagero.hook.status`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HookStatus {
    Ok,
    Timeout,
    Error,
    /// The app returned 404; treated as not implemented.
    Unimplemented,
}

impl HookStatus {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Ok => "ok",
            Self::Timeout => "timeout",
            Self::Error => "error",
            Self::Unimplemented => "unimplemented",
        }
    }
}

impl TryFrom<&str> for HookStatus {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, ()> {
        match value {
            "ok" => Ok(Self::Ok),
            "timeout" => Ok(Self::Timeout),
            "error" => Ok(Self::Error),
            "unimplemented" => Ok(Self::Unimplemented),
            _ => Err(()),
        }
    }
}

/// Values of `kagero.usage.cause`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum UsageCause {
    Suspend,
    Terminate,
}

impl UsageCause {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Suspend => "suspend",
            Self::Terminate => "terminate",
        }
    }
}

impl TryFrom<&str> for UsageCause {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, ()> {
        match value {
            "suspend" => Ok(Self::Suspend),
            "terminate" => Ok(Self::Terminate),
            _ => Err(()),
        }
    }
}

/// Values of `kagero.durable.step.kind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DurableStepKind {
    Step,
    Wait,
    Callback,
    Retry,
    Chained,
    Invoke,
    Context,
}

impl DurableStepKind {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Step => "step",
            Self::Wait => "wait",
            Self::Callback => "callback",
            Self::Retry => "retry",
            Self::Chained => "chained",
            Self::Invoke => "invoke",
            Self::Context => "context",
        }
    }
}

impl TryFrom<&str> for DurableStepKind {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, ()> {
        match value {
            "step" => Ok(Self::Step),
            "wait" => Ok(Self::Wait),
            "callback" => Ok(Self::Callback),
            "retry" => Ok(Self::Retry),
            "chained" => Ok(Self::Chained),
            "invoke" => Ok(Self::Invoke),
            "context" => Ok(Self::Context),
            _ => Err(()),
        }
    }
}

/// Values of `kagero.durable.status`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DurableStatus {
    Succeeded,
    Failed,
    TimedOut,
    Stopped,
    Running,
}

impl DurableStatus {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
            Self::TimedOut => "timed_out",
            Self::Stopped => "stopped",
            Self::Running => "running",
        }
    }
}

impl TryFrom<&str> for DurableStatus {
    type Error = ();

    fn try_from(value: &str) -> Result<Self, ()> {
        match value {
            "succeeded" => Ok(Self::Succeeded),
            "failed" => Ok(Self::Failed),
            "timed_out" => Ok(Self::TimedOut),
            "stopped" => Ok(Self::Stopped),
            "running" => Ok(Self::Running),
            _ => Err(()),
        }
    }
}
