/**
 * Generates typed constants for kagero semantic-convention attributes and
 * metrics from semconv/registry/*.yaml (Weaver registry schema).
 *
 * Outputs:
 *   packages/semconv/src/gen.ts            - TypeScript constants
 *   crates/kagero-agent/src/semconv_gen.rs - Rust constants
 *   docs/reference/attributes.md           - human-readable table
 *
 * The registry uses the Weaver schema (one metric per group, `type: metric`)
 * so that `weaver registry generate` can replace this script later without
 * changing the YAML source of truth.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

interface EnumMember {
  id: string;
  value: string;
  brief?: string;
}

interface KageroAnnotations {
  metric_label?: "allowed" | "forbidden";
}

interface Attribute {
  id: string;
  type: string | { members: EnumMember[] };
  stability?: string;
  brief?: string;
  examples?: string[];
  annotations?: { kagero?: KageroAnnotations };
}

interface Group {
  id: string;
  type: string;
  brief?: string;
  attributes?: Attribute[];
  // Weaver metric group shape: fields live on the group itself.
  metric_name?: string;
  instrument?: string;
  unit?: string;
  stability?: string;
}

interface Registry {
  groups: Group[];
}

const pkgDir = resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const repoRoot = resolve(pkgDir, "../..");
const registryDir = join(repoRoot, "semconv/registry");

const banner = "// @generated by packages/semconv/scripts/generate.ts — do not edit\n";

function constName(prefix: string, id: string): string {
  return `${prefix}_${id
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase()}`;
}

function typeName(id: string): string {
  const stripped = id.replace(/^kagero\./, "");
  return stripped
    .split(/[^A-Za-z0-9]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function variantName(memberId: string): string {
  let v = memberId
    .split(/[^A-Za-z0-9]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  if (v === "Self") v = "SelfValue";
  if (v === "" || /^[0-9]/.test(v)) v = `V${v}`;
  return v;
}

function screamingSnake(camel: string): string {
  return camel.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

/** Make text safe inside /** *\/ doc comments and markdown cells. */
function docText(brief: string | undefined): string {
  return (brief ?? "").replace(/\*\//g, "*\\/").replace(/\s+/g, " ").trim();
}

/** Escape a string for a Rust literal. */
function rustStr(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
}

const registryFiles = readdirSync(registryDir)
  .filter((f) => f.endsWith(".yaml") || f.endsWith(".yml"))
  .sort();
if (registryFiles.length === 0) throw new Error(`no registry files in ${registryDir}`);
const registries: Registry[] = registryFiles.map(
  (f) => parse(readFileSync(join(registryDir, f), "utf8")) as Registry,
);

const attributes: Attribute[] = [];
const metrics: Group[] = [];
for (const reg of registries) {
  for (const g of reg.groups) {
    for (const a of g.attributes ?? []) attributes.push(a);
    if (g.type === "metric" || g.type === "metric_group") {
      if (!g.metric_name) throw new Error(`metric group ${g.id} has no metric_name`);
      metrics.push(g);
    }
  }
}

// Duplicate-id and generated-name collision checks.
{
  const seen = new Map<string, number>();
  for (const a of attributes) seen.set(a.id, (seen.get(a.id) ?? 0) + 1);
  for (const m of metrics) seen.set(m.metric_name ?? "", (seen.get(m.metric_name ?? "") ?? 0) + 1);
  const dups = [...seen.entries()].filter(([, n]) => n > 1).map(([id]) => id);
  if (dups.length) throw new Error(`duplicate ids in registry: ${dups.join(", ")}`);

  const names = new Set<string>();
  for (const a of attributes) {
    const n = constName("ATTR", a.id);
    if (names.has(n)) throw new Error(`const name collision: ${n} (${a.id})`);
    names.add(n);
  }
  for (const m of metrics) {
    const n = constName("METRIC", m.metric_name ?? "");
    if (names.has(n)) throw new Error(`const name collision: ${n} (${m.metric_name})`);
    names.add(n);
  }
}

const enums = attributes.filter((a) => typeof a.type !== "string" && a.type.members);
const forbidden = attributes.filter((a) => a.annotations?.kagero?.metric_label === "forbidden");

// ---------- TypeScript ----------
const ts: string[] = [banner];
ts.push("// Attribute names\n");
for (const a of attributes) {
  const b = docText(a.brief);
  if (b) ts.push(`/** ${b} */`);
  ts.push(`export const ${constName("ATTR", a.id)} = ${JSON.stringify(a.id)} as const;\n`);
}
ts.push("\n// Metric names\n");
for (const m of metrics) {
  const b = docText(m.brief);
  if (b) ts.push(`/** ${b} */`);
  ts.push(
    `export const ${constName("METRIC", m.metric_name ?? "")} = ${JSON.stringify(m.metric_name)} as const;\n`,
  );
}
ts.push("\n// Metric definitions (name → shape)\n");
ts.push("export const KAGERO_METRICS = {");
for (const m of metrics) {
  ts.push(
    `  ${JSON.stringify(m.metric_name)}: { instrument: ${JSON.stringify(m.instrument)}, unit: ${JSON.stringify(m.unit ?? "")} },`,
  );
}
ts.push("} as const;\n");

ts.push("\n// Enumerated attribute values\n");
for (const a of enums) {
  if (typeof a.type !== "string" && a.type.members) {
    const name = typeName(a.id);
    const values = a.type.members.map((m) => m.value);
    ts.push(`/** Values of \`${a.id}\`. */`);
    ts.push(`export const ${screamingSnake(name)}_VALUES = ${JSON.stringify(values)} as const;`);
    ts.push(`export type ${name} = (typeof ${screamingSnake(name)}_VALUES)[number];\n`);
  }
}

ts.push("\n// ADR-008: attributes that must never appear on metric labels\n");
ts.push(
  `export const METRIC_LABEL_FORBIDDEN = ${JSON.stringify(forbidden.map((a) => a.id))} as const;`,
);
ts.push(
  `export const METRIC_LABEL_ALLOWED = ${JSON.stringify(
    attributes.filter((a) => a.annotations?.kagero?.metric_label === "allowed").map((a) => a.id),
  )} as const;\n`,
);

// Full id sets — drift tests scan sources for `kagero.*`/`service.*` etc.
// literals and require each to be registered here.
ts.push("\n// Registry completeness sets\n");
ts.push(
  `export const ALL_ATTRIBUTE_IDS = ${JSON.stringify(attributes.map((a) => a.id))} as const;`,
);
ts.push(
  `export const ALL_METRIC_NAMES = ${JSON.stringify(metrics.map((m) => m.metric_name))} as const;\n`,
);
writeFileSync(join(pkgDir, "src/gen.ts"), ts.join("\n"));

// ---------- Rust ----------
const rs: string[] = [
  banner.replace("//", "//!"),
  "//! kagero semantic-convention constants.",
  "#![allow(dead_code)]\n",
];
for (const a of attributes) {
  const b = docText(a.brief);
  if (b) rs.push(`/// ${b}`);
  rs.push(`pub const ${constName("ATTR", a.id)}: &str = ${rustStr(a.id)};`);
}
rs.push("");
for (const m of metrics) {
  const b = docText(m.brief);
  if (b) rs.push(`/// ${b}`);
  rs.push(
    `pub const ${constName("METRIC", m.metric_name ?? "")}: &str = ${rustStr(m.metric_name ?? "")};`,
  );
}
rs.push("");
rs.push("/// ADR-008: attributes that must never appear on metric labels.");
rs.push(
  `pub const METRIC_LABEL_FORBIDDEN: &[&str] = &[${forbidden.map((a) => rustStr(a.id)).join(", ")}];`,
);
rs.push("");
rs.push("/// Every registered attribute id — the source-drift test asserts that");
rs.push("/// every `kagero.*`/`service.*` literal in agent sources is listed here.");
rs.push(
  `pub const ALL_ATTRIBUTE_IDS: &[&str] = &[${attributes.map((a) => rustStr(a.id)).join(", ")}];`,
);
rs.push("/// Every registered metric name.");
rs.push(
  `pub const ALL_METRIC_NAMES: &[&str] = &[${metrics
    .map((m) => rustStr(m.metric_name ?? ""))
    .join(", ")}];`,
);
for (const a of enums) {
  if (typeof a.type !== "string" && a.type.members) {
    const name = typeName(a.id);
    rs.push(`\n/// Values of \`${a.id}\`.`);
    rs.push("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]");
    rs.push(`pub enum ${name} {`);
    for (const member of a.type.members) {
      const mb = docText(member.brief);
      if (mb) rs.push(`    /// ${mb}`);
      rs.push(`    ${variantName(member.id)},`);
    }
    rs.push("}\n");
    rs.push(`impl ${name} {`);
    rs.push("    pub const fn as_str(self) -> &'static str {");
    rs.push("        match self {");
    for (const member of a.type.members) {
      rs.push(`            Self::${variantName(member.id)} => ${rustStr(member.value)},`);
    }
    rs.push("        }\n    }\n}");
    rs.push(`\nimpl TryFrom<&str> for ${name} {`);
    rs.push("    type Error = ();\n");
    rs.push("    fn try_from(value: &str) -> Result<Self, ()> {");
    rs.push("        match value {");
    for (const member of a.type.members) {
      rs.push(`            ${rustStr(member.value)} => Ok(Self::${variantName(member.id)}),`);
    }
    rs.push("            _ => Err(()),\n        }\n    }\n}");
  }
}
const genRsPath = join(repoRoot, "crates/kagero-agent/src/semconv_gen.rs");
writeFileSync(genRsPath, `${rs.join("\n")}\n`);
execFileSync("rustfmt", ["--edition", "2024", genRsPath], { stdio: "inherit" });

// ---------- Docs ----------
const doc: string[] = [
  "# kagero 属性とメトリクス（生成）",
  "",
  "正本は `semconv/registry/` の YAML です。このファイルは `pnpm generate` で生成します。",
  "メトリクスのラベル可否は ADR-008 によります（forbidden の属性はメトリクスのラベルに使えません）。",
  "",
  "## 属性",
  "",
  "| 属性 | 型 | stability | metric label | 説明 |",
  "|---|---|---|---|---|",
];
for (const a of attributes) {
  const t = typeof a.type === "string" ? a.type : "enum";
  const label = a.annotations?.kagero?.metric_label ?? "—";
  const enumNote =
    typeof a.type !== "string" && a.type.members
      ? `（values: ${a.type.members.map((m) => `\`${m.value}\``).join(", ")}）`
      : "";
  doc.push(
    `| \`${a.id}\` | ${t} | ${a.stability ?? "development"} | ${label} | ${docText(a.brief).replace(/\|/g, "\\|")}${enumNote} |`,
  );
}
doc.push("", "## メトリクス", "", "| 名前 | instrument | 単位 | 説明 |", "|---|---|---|---|");
for (const m of metrics) {
  doc.push(
    `| \`${m.metric_name}\` | ${m.instrument} | ${m.unit ?? ""} | ${docText(m.brief).replace(/\|/g, "\\|")} |`,
  );
}
doc.push("");
mkdirSync(join(repoRoot, "docs/reference"), { recursive: true });
writeFileSync(join(repoRoot, "docs/reference/attributes.md"), doc.join("\n"));

// Format the TS output so `git diff` in CI stays clean.
const biome = join(repoRoot, "node_modules/.bin/biome");
if (existsSync(biome)) {
  execFileSync(biome, ["format", "--write", join(pkgDir, "src/gen.ts")], { stdio: "inherit" });
}

console.log(
  `generated ${attributes.length} attributes, ${metrics.length} metrics → gen.ts, semconv_gen.rs, attributes.md`,
);
